
package com.mindrevol.core.modules.notification.entity;

public enum NotificationType {
    FRIEND_REQUEST_RECEIVED,
    FRIEND_REQUEST_ACCEPTED,
    FRIEND_REQUEST_REJECTED,

    DM_NEW_MESSAGE,
    DM_SHARED_MOMENT,

    BOXCHAT_NEW_MESSAGE,
    BOXCHAT_SHARED_MOMENT,

    MOOD_NEW_STATUS_IN_BOX,
    MOOD_COMMENT_RECEIVED,
    MOOD_MENTIONED,

    MOMENT_NEW_FROM_FRIEND,
    MOMENT_NEW_IN_BOX,
    MOMENT_REPLIED_IN_DM,
    MOMENT_ASSIGNED_TO_JOURNEY,
    JOURNEY_NEW_CREATED_IN_BOX,

    UNSORTED_EXPIRING_SOON,
    UNSORTED_EXPIRED_DELETED,

    BOX_INVITE_RECEIVED,
    BOX_INVITE_ACCEPTED,
    BOX_MEMBER_JOINED,
    BOX_MEMBER_REMOVED,
    BOX_ROLE_UPDATED,
    BOX_DISSOLVED,

    AUTH_NEW_LOGIN,
    PROFILE_UPDATED,


    UPLOAD_FAILED_RETRY, FRIEND_REQUEST, FRIEND_ACCEPTED, REACTION, COMMENT, SYSTEM, JOURNEY_INVITE, CHECKIN, BOX_ADDED, BOX_INVITE

}
